import { describe, expect, it } from 'vitest'
import type { ForgePull } from '~/types/forge'
import {
  detectDependencyBot,
  normalizeVersion,
  parseDependencyUpdate,
  toDependencyPr,
  groupDependencyPrs,
  type DependencyPr
} from './dependency-updates'

function pull(overrides: Partial<ForgePull>): ForgePull {
  return {
    provider: 'github',
    id: '1',
    number: 1,
    title: '',
    state: 'open',
    ...overrides
  }
}

const repo: DependencyPr['repo'] = {
  provider: 'github',
  owner: 'acme',
  name: 'site',
  fullName: 'acme/site'
}

describe('detectDependencyBot', () => {
  it('detects Dependabot via author login', () => {
    expect(
      detectDependencyBot(pull({ author: { provider: 'github', login: 'dependabot[bot]' } }))
    ).toBe('dependabot')
  })

  it('detects Renovate via author login', () => {
    expect(
      detectDependencyBot(pull({ author: { provider: 'github', login: 'renovate[bot]' } }))
    ).toBe('renovate')
  })

  it('detects Renovate via the renovate/ branch when it runs under a human account', () => {
    expect(
      detectDependencyBot(
        pull({ author: { provider: 'github', login: 'octo' }, sourceBranch: 'renovate/astro-7.x' })
      )
    ).toBe('renovate')
  })

  it('detects Dependabot via the dependabot/ branch', () => {
    expect(detectDependencyBot(pull({ sourceBranch: 'dependabot/npm_and_yarn/astro-7.3.3' }))).toBe(
      'dependabot'
    )
  })

  it('detects via an automation marker in the body when the author is human', () => {
    expect(
      detectDependencyBot(
        pull({
          title: 'Update dependency astro to v7.3.3',
          author: { provider: 'github', login: 'octo' },
          body: 'This PR was generated by Renovate.'
        })
      )
    ).toBe('renovate')
    expect(
      detectDependencyBot(
        pull({
          title: 'Bump astro from 7.3.2 to 7.3.3',
          author: { provider: 'github', login: 'octo' },
          body: 'Dependabot will resolve any conflicts.'
        })
      )
    ).toBe('dependabot')
  })

  it('does not treat a title alone as a bot signal for a human PR', () => {
    expect(
      detectDependencyBot(
        pull({
          title: 'Update dependency astro to v7.3.3',
          author: { provider: 'github', login: 'octo' },
          sourceBranch: 'feat/deps',
          body: null
        })
      )
    ).toBeNull()
  })

  it('returns null for a normal human pull request', () => {
    expect(
      detectDependencyBot(pull({ title: 'Fix homepage bug', sourceBranch: 'fix/homepage' }))
    ).toBeNull()
  })
})

describe('normalizeVersion', () => {
  it('strips prefixes and lowercases', () => {
    expect(normalizeVersion('v7.3.3')).toBe('7.3.3')
    expect(normalizeVersion('^7.0.0')).toBe('7.0.0')
    expect(normalizeVersion('~1.2.3')).toBe('1.2.3')
    expect(normalizeVersion('  V2.0.0  ')).toBe('2.0.0')
  })
})

describe('parseDependencyUpdate', () => {
  it('parses a plain Dependabot bump', () => {
    const p = parseDependencyUpdate('Bump astro from 7.3.2 to 7.3.3', 'dependabot')
    expect(p).toMatchObject({ bot: 'dependabot', dependency: 'astro', from: '7.3.2', to: '7.3.3' })
    expect(p?.key).toBe('astro:7.3.3')
  })

  it('parses a conventional-commit Dependabot bump', () => {
    const p = parseDependencyUpdate(
      'build(deps): bump aws-sdk-kms from 1.95.0 to 1.96.0',
      'dependabot'
    )
    expect(p?.dependency).toBe('aws-sdk-kms')
    expect(p?.from).toBe('1.95.0')
    expect(p?.to).toBe('1.96.0')
  })

  it('strips a Dependabot directory suffix from the target version', () => {
    const p = parseDependencyUpdate('Bump foo from 1.0.0 to 1.1.0 in /frontend', 'dependabot')
    expect(p?.to).toBe('1.1.0')
    expect(p?.dependency).toBe('foo')
  })

  it('parses a plain Renovate update', () => {
    const p = parseDependencyUpdate('Update dependency astro to v7.3.3', 'renovate')
    expect(p).toMatchObject({ bot: 'renovate', dependency: 'astro', to: '7.3.3' })
    expect(p?.key).toBe('astro:7.3.3')
  })

  it('parses a conventional-commit Renovate update', () => {
    const p = parseDependencyUpdate(
      'fix(deps): update dependency @astrojs/check to v0.9.10',
      'renovate'
    )
    expect(p?.dependency).toBe('@astrojs/check')
    expect(p?.to).toBe('0.9.10')
  })

  it('groups same dependency+target that share a source major, ignoring minor/patch', () => {
    const a = parseDependencyUpdate('Bump astro from 7.3.1 to 7.3.3', 'dependabot')!
    const b = parseDependencyUpdate('Bump astro from 7.3.2 to 7.3.3', 'dependabot')!
    expect(a.from).toBe('7.3.1')
    expect(b.from).toBe('7.3.2')
    const aPr = toDependencyPr(
      pull({ title: 'Bump astro from 7.3.1 to 7.3.3', sourceBranch: 'dependabot/x' }),
      repo
    )!
    const bPr = toDependencyPr(
      pull({ title: 'Bump astro from 7.3.2 to 7.3.3', sourceBranch: 'dependabot/y' }),
      { ...repo, name: 'web', fullName: 'acme/web' }
    )!
    const groups = groupDependencyPrs([aPr, bPr])
    expect(groups).toHaveLength(1)
    expect(groups[0]!.items).toHaveLength(2)
    expect(a.key).toBe(b.key)
  })

  it('returns null for multi-dependency group titles', () => {
    expect(parseDependencyUpdate('Update all non-major dependencies', 'renovate')).toBeNull()
    expect(
      parseDependencyUpdate('Bump the eslint group with 2 updates in /app', 'dependabot')
    ).toBeNull()
  })

  it('does not cross-parse a dependabot title under renovate', () => {
    expect(parseDependencyUpdate('Bump astro from 1 to 2', 'renovate')).toBeNull()
  })
})

describe('toDependencyPr / groupDependencyPrs', () => {
  it('parses the source version from a Renovate body', () => {
    const pr = toDependencyPr(
      pull({
        title: 'Update dependency astro to v7.3.3',
        sourceBranch: 'renovate/astro-7.x',
        body: 'This PR contains the following updates:\n\n| Package | Change |\n| --- | --- |\n| [astro]() | `^6.0.0` -> `^7.0.0` |'
      }),
      repo
    )!
    expect(pr.parsed?.dependency).toBe('astro')
    expect(pr.parsed?.from).toBe('6.0.0')
  })

  it('separates same dependency+target when source majors differ', () => {
    const minor = toDependencyPr(
      pull({ title: 'Bump astro from 7.3.2 to 7.3.3', sourceBranch: 'dependabot/a' }),
      repo
    )!
    const major = toDependencyPr(
      pull({ title: 'Bump astro from 5.4.2 to 7.3.3', sourceBranch: 'dependabot/b' }),
      { ...repo, name: 'web', fullName: 'acme/web' }
    )!
    const groups = groupDependencyPrs([minor, major])
    expect(groups).toHaveLength(2)
    expect(groups.every((g) => g.items.length === 1)).toBe(true)
  })

  it('groups a Dependabot and Renovate PR for the same update together', () => {
    const dependabot = toDependencyPr(
      pull({ title: 'Bump astro from 7.3.2 to 7.3.3', sourceBranch: 'dependabot/astro' }),
      repo
    )!
    const renovate = toDependencyPr(
      pull({
        title: 'Update dependency astro to v7.3.3',
        sourceBranch: 'renovate/astro-7.x',
        body: '| [astro]() | `^7.3.1` -> `^7.3.3` |'
      }),
      { ...repo, name: 'web', fullName: 'acme/web' }
    )!
    const groups = groupDependencyPrs([dependabot, renovate])
    expect(groups).toHaveLength(1)
    expect(groups[0]!.items).toHaveLength(2)
  })

  it('groups identical updates across repos into one meaningful group', () => {
    const prA = toDependencyPr(
      pull({ title: 'Update dependency astro to v7.3.3', sourceBranch: 'renovate/astro-7.x' }),
      repo
    )!
    const prB = toDependencyPr(
      pull({
        title: 'Update dependency astro to v7.3.3',
        sourceBranch: 'renovate/astro-7.x',
        author: { provider: 'github', login: 'renovate[bot]' }
      }),
      { ...repo, name: 'web', fullName: 'acme/web' }
    )!
    const groups = groupDependencyPrs([prA, prB])
    expect(groups).toHaveLength(1)
    expect(groups[0]!.items).toHaveLength(2)
    expect(groups[0]!.unparsable).toBe(false)
    expect(groups[0]!.name).toBe('Update astro to 7.3.3')
  })

  it('keeps broad group PRs as unparsable singletons instead of merging them', () => {
    const prA = toDependencyPr(
      pull({ title: 'Update all non-major dependencies', sourceBranch: 'renovate/all-nonmajor' }),
      repo
    )!
    const prB = toDependencyPr(
      pull({ title: 'Update all non-major dependencies', sourceBranch: 'renovate/all-nonmajor' }),
      { ...repo, name: 'web', fullName: 'acme/web' }
    )!
    const groups = groupDependencyPrs([prA, prB])
    expect(groups).toHaveLength(2)
    for (const g of groups) {
      expect(g.unparsable).toBe(true)
      expect(g.items).toHaveLength(1)
    }
  })

  it('filters out non-dependency PRs', () => {
    const pr = toDependencyPr(
      pull({ title: 'Shop spring sale', sourceBranch: 'feature/sale' }),
      repo
    )
    expect(pr).toBeNull()
  })

  it('sorts parsed groups before unparsable ones', () => {
    const parsed = toDependencyPr(
      pull({ title: 'Update dependency astro to v7.3.3', sourceBranch: 'renovate/astro' }),
      repo
    )!
    const unparsed = toDependencyPr(
      pull({ title: 'Update all non-major dependencies', sourceBranch: 'renovate/all' }),
      repo
    )!
    const groups = groupDependencyPrs([unparsed, parsed])
    expect(groups.map((g) => g.unparsable)).toEqual([false, true])
  })
})
